server:
  port: 8989

spring:
  application:
    name: IdentityHub

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/identityhub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: Aditya@2202
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: Y2Y4NzA2ODU3N2NhZjEzZjNkNzNkY_IDENTITY_HUB_AProductForUserManagement2026
  expiration: 1800000 #30 min

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173